# Not using persistent volumes in dev mode
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - name: sql-server
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "23--HFEWF-f23f32wg8w3hg38gh3g3g3g3" # normally you would use a secret

---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-srv
spec:
  selector:
    app: sql-server
  type: ClusterIP
  ports:
    - name: sql-db
      protocol: TCP
      port: 1433
      targetPort: 1433
