name: tests-programs

on:
  pull_request:
    paths:
      - "programs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd database/docker
          docker build . -t chihweidavidliu/mssql-test-db
          docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=23--HFEWF-f23f32wg8w3hg38gh3g3g3g3' -p 1433:1433 --name test-db -d chihweidavidliu/mssql-test-db
          sleep 20
          cd ../
          npm install && npm run migrate-db
          cd ../programs
          npm install && npm run test:ci
