name: tests-programs

on:
  pull_request:
    paths:
      - "programs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run test-local
